### ISSUE TITLE
Erro na página de Alunos

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#10]
Ao acessar a página de alunos, ocorreu o erro abaixo:

![Screenshot from 2024-07-25 15-24-09](https://github.com/user-attachments/assets/862a3fc0-7a2a-4b24-b2ee-4bd29389d616)

![Screenshot from 2024-07-25 15-22-59](https://github.com/user-attachments/assets/97ed94e3-1dea-42a8-bd91-e9fdc149b5e1)

**Comment by jgoa156** [comment]
A chave do objeto estava incorreta. Já corrigido.

**Comment by NicollyAlves** [comment]
Aparece a listagem de alunos sem erros.

![Captura de tela de 2024-08-02 09-29-03](https://github.com/user-attachments/assets/4729acaf-0a17-43ed-b2e7-df20c9c7b0cd)
