### ISSUE TITLE
Na página de coordenadores, não aparece o coordenador Admin Teste

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#11]
Vide imagem.

![Screenshot from 2024-07-25 15-26-22](https://github.com/user-attachments/assets/c7025076-cf2c-4d30-96ad-88076ae0de26)

**Comment by jgoa156** [comment]
Na verdade a funcionalidade realmente evitava de listar o usuário que está visualizando a lista. O filtro foi removido e foi adicionado apenas um condicional de forma que o usuário não execute operações de risco na própria conta.
