### ISSUE TITLE
O sistema permite senhas muito simples.

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#12]
Ao definir a senha do meu usuário, o sistema deixou eu colocar a senha 123. Obrigar o usuário a colocar senhas maiores e mais complexas.

![Screenshot from 2024-07-25 14-50-53](https://github.com/user-attachments/assets/f7ca4ecb-c2f9-49ef-8901-f2f995661b30)

**Comment by jgoa156** [comment]
Feito.
![image](https://github.com/user-attachments/assets/e6c03925-a917-4a02-8d24-3348e69cebfd)
![image](https://github.com/user-attachments/assets/6cb242bf-f89a-4966-88a1-60ae1b141b6d)
![image](https://github.com/user-attachments/assets/b3fb1976-2dbe-4c1f-90b6-4ad61e0bb572)

**Comment by NicollyAlves** [comment]
Não permite mais senhas simples

![Captura de tela de 2024-08-02 09-26-24](https://github.com/user-attachments/assets/14d19137-276a-445b-84e4-400f2ce00c40)
