### ISSUE TITLE
Opção de Editar ou Resetar Senha dos secretários não funciona

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#13]
Tentei editar os dados do usuário "Secretary", mas ao clicar na opção não acontece nada. O mesmo acontece com a opção "Resetar senha".

![Screenshot from 2024-07-25 15-56-00](https://github.com/user-attachments/assets/2a6e5a60-c54d-4113-a6dd-6a7671bf57b8)

**Comment by jgoa156** [comment]
A feature realmente não tinha sido implementada, mas já está sendo.
