### ISSUE TITLE
Erro nos status

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#14]
Na página de submissões, para uma submissõa recem adicionada, uma hora ela é chamada de "pendente" e outra hora de "submetido".

![Screenshot from 2024-07-25 16-02-43](https://github.com/user-attachments/assets/1f5c01b2-625b-4189-8926-d8bbf5dea022)

**Comment by jgoa156** [comment]
Os adjetivos foram trocados para "Pendente" e nos verbos ficou como "submeteu".

**Comment by NicollyAlves** [comment]
As submissões aparecem como "Pendente" no lugar de "Submetido"

![Captura de tela de 2024-08-01 21-39-01](https://github.com/user-attachments/assets/48f2739c-0ce1-4021-a796-e7589cc366a1)
![Captura de tela de 2024-08-01 21-39-41](https://github.com/user-attachments/assets/bbe68a0a-a345-4eba-924c-80b815d5c10e)
