### ISSUE TITLE
Erro durante a aprovação em lote

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#15]
Ao aprovar as submissóes em lote (opção Aprovar selecionados), a aplicação apresenta um erro. O mesmo erro acontrece quando eu clico em "Rejeitar selecionados".

![Screenshot from 2024-07-25 16-05-33](https://github.com/user-attachments/assets/8e7d29c6-7d86-4454-a1ef-2c48c30dd3ee)

**Comment by jgoa156** [comment]
Foi encontrado um erro no Content Type da requisição (agora alterado para application/json)
![image](https://github.com/user-attachments/assets/a5b8f5fa-213e-486e-9775-c25b5afaeff2)

**Comment by NicollyAlves** [comment]
Opção de mudar o status de múltiplas submissões está funcionando corretamente 

![Captura de tela de 2024-08-01 21-31-47](https://github.com/user-attachments/assets/35c85272-3f9e-4cd3-b293-386cb453c9f6)
![Captura de tela de 2024-08-01 21-31-59](https://github.com/user-attachments/assets/327b8b2d-9c71-438c-820a-25231c7c9428)
