### ISSUE TITLE
Possibilidade de revisar o parecer

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#16]
Depois que a submissão foi aprovada ou rejeitada, o coordenador não pode rever o seu parecer. Acho que seria bom adicionarmos essa possibilidade.

![Screenshot from 2024-07-25 16-14-07](https://github.com/user-attachments/assets/26c1d044-1d96-4009-b688-561ee299b302)

**Comment by jgoa156** [comment]
Sobre isso, é possível alterar o status de submissões já aprovadas? Pois se for o caso, essa regra também será removida.
![image](https://github.com/user-attachments/assets/e215f1a3-9363-4726-80ea-918c4206c89d)

**Comment by jgoa156** [comment]
Eu adicionei a opção de modificar o status caso a submissão tenha sido rejeitada também. Secretários continuam podendo somente pré-aprovar uma submissão e apenas caso a submissão esteja como pendente. Submissões já aprovadas não podem ser alteradas.

**Comment by NicollyAlves** [comment]
As submissões recusadas podem ter seu status alterado. As aprovadas não podem.

![Captura de tela de 2024-08-01 21-25-57](https://github.com/user-attachments/assets/73144b05-ac4f-41f8-b12c-7ce3c4ca37be)
