### ISSUE TITLE
Mostrar usuários com status inativo

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#17]
Eu desativei a conta de um secretário, e eu não consegui mais visualizar essa conta na aplicação. Na  listagem de secretários (e dos demais usuários), seria importante listar os usuários desativados. Isso é importante, pq se eu tentar criar uma nova conta para o usuário, eu não vou conseguir por que já existe um usuário com o email dele, mesmo que desativado. Mostrar os usuários desativados, com a opção de reativar tais contas.

![Screenshot from 2024-07-25 16-18-02](https://github.com/user-attachments/assets/976468e5-085a-4d12-8717-29af5f8d4d30)

**Comment by jgoa156** [comment]
A opção já era possível antes, entretanto, a opção de reativar o usuário não estava presente, mas já foi implementada.
![image](https://github.com/user-attachments/assets/0182fa7b-11da-4ac6-aef9-d3017c3ef039)

**Comment by NicollyAlves** [comment]
Possui o filtro para acessar os usuários inativos e a opção de reativar usuário está funcionando 

![Captura de tela de 2024-08-01 21-15-25](https://github.com/user-attachments/assets/8840def7-334e-4ec2-9c6a-8d380bc34b27)
![Captura de tela de 2024-08-01 21-15-38](https://github.com/user-attachments/assets/32e97b10-0f73-45a3-ae61-7a7b2b486d6e)
