### ISSUE TITLE
No painel, número de submissões aprovadas não é atualizado

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#18]
Mesmo aprovando um conjunto de submissões, o card do painel que mostra o número de submissões aprovadas não é atualizado.

![Screenshot from 2024-07-25 16-23-23](https://github.com/user-attachments/assets/7e82f30e-14f7-4388-9ce4-bde4e5afa80e)

**Comment by jgoa156** [comment]
Nome da variável estava incorreto
![image](https://github.com/user-attachments/assets/cbd0a804-ca8f-41ef-883b-f91af28a6232)

**Comment by NicollyAlves** [comment]
O número de submissões está sendo atualizado

![Captura de tela de 2024-08-01 20-55-27](https://github.com/user-attachments/assets/0873210f-634d-4d1c-bdef-f82d77c619b1)
