### ISSUE TITLE
Adicionar mecanismo para verificar validade do CPF do usuário

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#4]
![Screenshot from 2024-07-25 14-43-00](https://github.com/user-attachments/assets/387f4741-937c-4354-b1eb-dfb9f4834ff0)

O sistema está permitindo a inclusão de usuários com CPF inválido. O CPF é importante, pois ele normalmente é usado para cruzar os dados com outras bases, como do ecampus. Adicionar verificador, tanto na criação quanto na edição dos dados do usuário.

**Comment by jgoa156** [comment]
O algoritmo de validação de CPF até funciona corretamente mas realmente não constavam os casos conhecidos de CPFs inválidos (neste caso, CPFs com números repetidos dessa forma).
A funcionalidade já foi corrigida e será implementada no próximo deploy.

**Comment by NicollyAlves** [comment]
Na edição ele não permite com o cpf inválido
![Captura de tela de 2024-08-02 09-41-22](https://github.com/user-attachments/assets/325260ee-243d-4cac-b21c-6de4cea9c90f)

Na criação de um usuário com o CPF inválido, ele mostra o erro, mas ainda cria o usuário, mas com o campo de cpf vazio
![Captura de tela de 2024-08-02 09-42-35](https://github.com/user-attachments/assets/fdb94cf4-e88e-4655-8c78-b998aa488ff3)
![Captura de tela de 2024-08-02 09-44-21](https://github.com/user-attachments/assets/ef0af22c-9caf-44da-ab67-e4b2c4ddee0a)
