### ISSUE TITLE
Mensagem ao criar uma nova conta

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#5]
Ao adicionar um novo usuário, é importante notificar que o novo usuário irá receber no seu email com informações de acesso ao sistema. A seguinte mensagem pode ser usada: Usuário(a) adicionado(a) com sucesso. O(A) novo(a) usuário(a) irá receber um email com instruções de acesso ao sistema.

![Screenshot from 2024-07-25 14-47-31](https://github.com/user-attachments/assets/956788ae-cbdb-4469-b312-2a5b0a6de0d1)

**Comment by jgoa156** [comment]
A frase agora é: "Usuário(a) adicionado(a) com sucesso. Será enviado um email com instruções de acesso ao sistema para o email cadastrado.".
A funcionalidade tomará efeito no próximo deploy.

**Comment by NicollyAlves** [comment]
![Captura de tela de 2024-08-02 09-39-46](https://github.com/user-attachments/assets/4db4e36b-e424-41b4-aaec-3993e7332942)
