### ISSUE TITLE
Erro ao adicionar uma atividade

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#7]
Deu um erro ao adiconar uma atividade. Acho que o sistema não está permitindo adicionar PDF com mais de 1.0 MB. Acho que podemos mudar esse limite para 10MB. E seria bom adicionar uma informação sobre o limite do tamanho de arquivos aceito. Por exemplo, podemos trocar o título "Envie aqui o arquivo (em PDF) do seu certificado*" para "Envie aqui o arquivo (em PDF) do seu certificado* (Max 10.0 MB)"

Quando o erro for causado por causa do tamanho do arquivo submetido, seria bom avisar o usuário que o sistema não permite arquivos maiores do que 10 MB.

![Screenshot from 2024-07-25 15-01-10](https://github.com/user-attachments/assets/45bd7749-8267-48cf-b731-aac107bf1666)

**Comment by jgoa156** [comment]
O erro ocorreu devido a um parâmetro do NGINX em produção que não permite envios de requisições com mais de 1mb. O tamanho máximo arquivo na verdade é 5mb e o erro aparece caso o arquivo seja maior que isso, porém eu posso aumentar o tamanho para 10mb.
Também acrescentarei um aviso na tela.
