### ISSUE TITLE
CPF com problema na listagem de submissões

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#8]
Ao abrir uma submissão na página de submissões, o CPF do usuário é mostrado vazio (aparece só o traço). Acho que nós podemos remover o CPF desse card, para que ele fique com o mesmo número de linhas do card à direita.

![Screenshot from 2024-07-25 15-10-12](https://github.com/user-attachments/assets/043efe5d-2f87-4f08-99bb-0990e6b90574)

**Comment by jgoa156** [comment]
No caso o CPF não é exibido pois o usuário não possui CPF cadastrado. Foi adicionado uma regra para ocultar o campo caso o CPF não exista. Entretanto, seria bom reavaliar a necessidade de existir o campo CPF (que no início do projeto foi determinado que seria opcional).
