### ISSUE TITLE
Erro no breadcrump

### ISSUE THREAD

**Issue by dbfernandes** [jgoa156/pyramid-ufam#9]
Na página de Submissões por grupo de atividades (página do coordenador), o breadcrump sempre aparece com o grupo de pequisa "extensao", mesmo que o usuário esteja no grupo de "Pesquisa" ou "Ensino".

![Screenshot from 2024-07-25 15-15-12](https://github.com/user-attachments/assets/dc109b29-c170-4115-b18c-d6348c4b3da6)

**Comment by jgoa156** [comment]
O objeto dos títulos não estava sendo usado no Breadcrumb. Já corrigido.

**Comment by NicollyAlves** [comment]
Cada atividade aparece onde deveria

![Captura de tela de 2024-08-02 09-31-48](https://github.com/user-attachments/assets/14bad251-89ec-41fa-913b-a83f8d69e3f2)
![Captura de tela de 2024-08-02 09-32-11](https://github.com/user-attachments/assets/94e24e22-65d2-4e42-8f6b-a62b58668bdd)
![Captura de tela de 2024-08-02 09-32-29](https://github.com/user-attachments/assets/1ecca43f-0584-4a13-8452-5c4c8a7c7a3a)
